### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by GeoffreyPlitt** [johntalton/mcp23017#1]
Very interested to use this. Could you throw up a full example?

**Comment by johntalton** [comment]
First, this is a beta (maybe alpha) version so far, and thus master is tracking dev and changes (aka breaks) a lot.

Second, the dependencies are not published npms. And specifically `rasbus` also is a wrapper for several i2c and spi libraries. Though the lib itself just assumes the interface (duck for now, typescript later maybe)

Third, example/client is the current working app.  It follows similar style used in other repo here (aka boschieu etc).  The current examples focus less on creating Gpio style access (though it is stubbed in and headed in that direction as per notes etc) and more on managing the chip settings directly as a low level api.

Node, the Gpio will follow the `onoff` style api and work interchangeably with it.  The chip has two interrupts that can be managed via `onoff` and feed back to this lib (other gpio libs should also work)

Last, the usefulness of many of the existing and target features add a complexity not found in other (all?) libraries for the mcp23 chips.  And as such usefulness of such added complexity weight against any performance gains may be negligible under V8 runtimes  (as examples. supporting both 8bit and 16bit poll mode, as well as the interlaced and dual-blocks addressing mode may provide little production usages ... time will tell :) )


I would be interested in any use cases / features etc you have in mind.
thank

**Comment by GeoffreyPlitt** [comment]
Gotcha. So is this polling-only, or is it interrupt-driven? Looking for something that doesn't eat CPU unless buttons are pressed.

**Comment by GeoffreyPlitt** [comment]
Killer explanation, thank you!
